# This is a basic workflow to help you get started with Actions
on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "dev-gm"
          user-email: "github@gavinm.us"
          message: "Automatically compiled typescript"
          directories: ./
